; Script generated by the Antigravity AI assistant.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ROM-Rot"
#define MyAppVersion "2.5"
#define MyAppPublisher "Nazariev-S"
#define MyAppPublisherURL "https://github.com/AlexeyNazariev"
#define MyAppFileDirSynth "build\LofiChiptuneSynth_artefacts\Release\VST3\ROM-Rot.vst3"
#define MyAppFileDirFX "build\LofiChiptuneSynthFX_artefacts\Release\VST3\ROM-Rot FX.vst3"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={{5A4F0D1B-0DF5-4E3F-FF2E-93A977ADB9C2}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppPublisherURL}
DefaultDirName={commoncf}\VST3
DirExistsWarning=no
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=license.txt
PrivilegesRequired=admin
OutputBaseFilename=ROM-Rot_v2.5_Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

; Custom Graphics (Modern Wizard Style)
WizardImageFile=installer_bg.bmp
WizardSmallImageFile=installer_icon.bmp

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Files]
Source: "{#MyAppFileDirSynth}\*"; DestDir: "{app}\ROM-Rot.vst3"; Flags: recursesubdirs createallsubdirs ignoreversion
Source: "{#MyAppFileDirFX}\*"; DestDir: "{app}\ROM-Rot FX.vst3"; Flags: recursesubdirs createallsubdirs ignoreversion

[Code]
// Custom Inno Setup script logic can go here if needed.
