#pragma once

#include <juce_core/juce_core.h>

/**
 * @brief Класс-утилита RetroRomExporter для экспорта параметров синтезатора в форматы ретро-платформ.
 * Поддерживаются:
 * 1. Формат PICO-8 SFX (код на Lua и строковые параметры для SFX-трекера).
 * 2. Ассемблерные таблицы данных для NES (чип Ricoh 2A03 для Famicom/NES).
 */
class RetroRomExporter
{
public:
    /**
     * @brief Экспорт в Lua код и спецификацию трекера PICO-8.
     */
    static juce::String exportToPico8(int waveType, float pulseWidth, float attack, float decay, float sustain, float release, float vibe)
    {
        juce::String waveName;
        int pico8WaveIndex = 0; // 0=triangle, 1=tilted saw, 2=saw, 3=square, 4=pulse, 5=noise
        
        switch (waveType)
        {
            case 0: waveName = "Triangle/Sine (mapped to Triangle)"; pico8WaveIndex = 0; break;
            case 1: waveName = "Stepped Triangle (Triangle)"; pico8WaveIndex = 0; break;
            case 2: waveName = "Sawtooth"; pico8WaveIndex = 2; break;
            case 3: 
            default:
                if (pulseWidth < 0.25f || pulseWidth > 0.75f)
                {
                    waveName = "Narrow Pulse (12.5% duty)";
                    pico8WaveIndex = 4; // pulse
                }
                else
                {
                    waveName = "Square (50% duty)";
                    pico8WaveIndex = 3; // square
                }
                break;
        }

        // В PICO-8 огибающие имеют дискретные шаги от 0 до 255.
        // Маппим наши параметры ADSR в параметры трекера PICO-8
        int p8Attack = juce::jlimit(0, 7, static_cast<int>(attack * 7.0f));
        int p8Decay = juce::jlimit(0, 7, static_cast<int>(decay * 7.0f));
        int p8Sustain = juce::jlimit(0, 15, static_cast<int>(sustain * 15.0f));
        int p8Release = juce::jlimit(0, 7, static_cast<int>(release * 7.0f));
        
        int p8Speed = juce::jlimit(1, 120, static_cast<int>(juce::jmap(vibe, 16.0f, 4.0f))); // скорость воспроизведения SFX
        
        juce::String output;
        output << "-- PICO-8 SFX Instrument Config\n"
               << "-- Generated by Antigravity VST3\n"
               << "-- Active Waveform: " << waveName << "\n\n"
               << "-- SFX RAM byte representation:\n"
               << "-- [speed:" << juce::String::toHexString(p8Speed).paddedLeft('0', 2)
               << "][loop_start:00][loop_end:00]\n"
               << "-- ADSR envelope steps:\n"
               << "-- Attack:  " << p8Attack << " (0-7)\n"
               << "-- Decay:   " << p8Decay << " (0-7)\n"
               << "-- Sustain: " << p8Sustain << " (0-15)\n"
               << "-- Release: " << p8Release << " (0-7)\n\n"
               << "-- PICO-8 Lua custom SFX setup function:\n"
               << "function init_sfx_instrument()\n"
               << "  poke(0x3200, 0x" << juce::String::toHexString(pico8WaveIndex) << ") -- Set wave type\n"
               << "  poke(0x3201, " << p8Attack << ") -- Set Attack\n"
               << "  poke(0x3202, " << p8Decay << ") -- Set Decay\n"
               << "  poke(0x3203, " << p8Sustain << ") -- Set Sustain\n"
               << "  poke(0x3204, " << p8Release << ") -- Set Release\n"
               << "end";
               
        return output;
    }

    /**
     * @brief Экспорт в ассемблерные таблицы данных NES 2A03 (6502 Assembly).
     */
    static juce::String exportToNesAssembly(int waveType, float pulseWidth, float attack, float decay, float sustain, float release)
    {
        juce::String output;
        output << "; =========================================\n"
               << "; NES 2A03 APU REGISTER INITIALIZATION DATA\n"
               << "; Generated by Antigravity VST3 Synthesizer\n"
               << "; =========================================\n\n";

        // NES APU имеет: SQ1 ($4000-$4003), SQ2 ($4004-$4007), TRI ($4008-$400B), NOISE ($400C-$400F)
        if (waveType == 3) // Pulse/Square
        {
            // Определяем скважность (Duty Cycle) для NES:
            // %00 = 12.5%, %01 = 25%, %10 = 50%, %11 = 75% (зеркало 25%)
            unsigned char dutyBits = 0x80; // 50% по умолчанию (%10)
            juce::String dutyDesc = "50% Duty Cycle";
            
            float absPW = std::abs(pulseWidth - 0.5f);
            if (absPW > 0.3f)
            {
                dutyBits = 0x00; // 12.5% (%00)
                dutyDesc = "12.5% Duty Cycle";
            }
            else if (absPW > 0.1f)
            {
                dutyBits = 0x40; // 25% (%01)
                dutyDesc = "25% Duty Cycle";
            }
            
            // NES Огибающая громкости ($4000: DDLC VVVV)
            // D = Duty, L = Length Counter Halt, C = Constant Volume flag, V = Volume/Decay rate
            unsigned char volumeRegister = dutyBits;
            
            // Если sustain близок к 1.0, делаем постоянную громкость
            if (sustain > 0.8f)
            {
                unsigned char vol = static_cast<unsigned char>(sustain * 15.0f) & 0x0F;
                volumeRegister |= 0x30; // Устанавливаем Constant Volume и Halt Length Counter
                volumeRegister |= vol;
            }
            else
            {
                // Имитируем огибающую затухания
                unsigned char decayRate = static_cast<unsigned char>((1.0f - decay) * 15.0f) & 0x0F;
                volumeRegister |= 0x10; // Выключаем постоянную громкость (включаем внутренний генератор спада)
                volumeRegister |= decayRate;
            }
            
            output << "; Pulse Channel 1 Settings (" << dutyDesc << ")\n"
                   << "NES_SQ1_VOL:   .byte $" << juce::String::toHexString(static_cast<int>(volumeRegister)).paddedLeft('0', 2) 
                   << "   ; Duty, Loop, Constant Vol, Vol/Decay\n"
                   << "NES_SQ1_SWEEP: .byte $08      ; Sweep disabled\n"
                   << "NES_SQ1_LO:    .byte $00      ; Frequency low byte (dynamic)\n"
                   << "NES_SQ1_HI:    .byte $08      ; Frequency high byte + Length counter\n";
        }
        else if (waveType == 1 || waveType == 0) // Triangle
        {
            // Регистрами треугольного канала являются $4008-$400B
            // $4008: CRRR RRRR (C = Control/Length Halt, R = Linear Counter reload value)
            unsigned char triLinearVal = static_cast<unsigned char>(release * 127.0f) & 0x7F;
            if (sustain > 0.5f) triLinearVal |= 0x80; // Halt линейного счетчика при зажатой клавише
            
            output << "; Triangle Channel Settings\n"
                   << "NES_TRI_LINEAR: .byte $" << juce::String::toHexString(static_cast<int>(triLinearVal)).paddedLeft('0', 2)
                   << "   ; Control flag, Linear counter reload\n"
                   << "NES_TRI_LO:     .byte $00      ; Frequency low byte (dynamic)\n"
                   << "NES_TRI_HI:     .byte $08      ; Frequency high byte + Length counter\n";
        }
        else // Пила (на NES пила отсутствовала в APU, выводим заглушку или эмуляцию через сэмплы)
        {
            output << "; Sawtooth is not natively supported by NES 2A03 APU!\n"
                   << "; Emulation via DPCM or Expansion chip (VRC6) is required.\n"
                   << "; Showing fallback VRC6 Sawtooth Channel Register registers:\n"
                   << "VRC6_SAW_VOL:   .byte $07      ; Max volume accumulator\n"
                   << "VRC6_SAW_LO:    .byte $00      ; Frequency low byte\n"
                   << "VRC6_SAW_HI:    .byte $80      ; Frequency high byte + Enable\n";
        }
        
        return output;
    }

    /**
     * @brief Экспорт в формат YM2612 для Sega Genesis (YM2612 FM-регистры).
     */
    static juce::String exportToSegaYM2612(int waveType, float pulseWidth, float attack, float decay, float sustain, float release)
    {
        juce::ignoreUnused(waveType, pulseWidth);
        
        int ar = juce::jlimit(0, 31, static_cast<int>((1.0f - attack) * 31.0f));
        int dr = juce::jlimit(0, 31, static_cast<int>((1.0f - decay) * 31.0f));
        int sl = juce::jlimit(0, 15, static_cast<int>((1.0f - sustain) * 15.0f));
        int rr = juce::jlimit(0, 15, static_cast<int>((1.0f - release) * 15.0f));

        // Стандартные значения для регистров 4-х операторов YM2612:
        // Regs 30-3C: Detune (DT1) & Multiple (MUL)
        int r30 = 0x01; // DT1 = 0, MUL = 1
        
        // Regs 40-4C: Total Level (TL)
        int r40_op1 = 0x18;
        int r40_op2 = 0x20;
        int r40_op3 = 0x10;
        int r40_op4 = 0x00; // OP4 - несущий (Carrier), громкость на максимум

        // Regs 50-5C: Key Scale (KS) & Attack Rate (AR)
        int r50 = ar & 0x1F;

        // Regs 60-6C: AM Enable (AM) & Decay Rate (DR)
        int r60 = dr & 0x1F;

        // Regs 70-7C: Sustain Rate (SR)
        int r70 = 0x02;

        // Regs 80-8C: Sustain Level (SL) & Release Rate (RR)
        int r80 = (sl << 4) | (rr & 0x0F);

        // Regs 90-9C: SSG-EG
        int r90 = 0x00;

        // Reg B0: Feedback & Algorithm (FB=6, ALG=4)
        int rB0 = 0x34;

        // Reg B4: Pan (L/R) & AMS/FMS
        int rB4 = 0xC0;

        juce::String output;
        output << "// =========================================\n"
               << "// SEGA GENESIS YM2612 INSTRUMENT REGISTER DATA\n"
               << "// Generated by Antigravity VST3 Synthesizer\n"
               << "// =========================================\n\n"
               << "// Scaled ADSR parameters to register values:\n"
               << "// AR (Attack Rate, 0-31):  " << ar << "\n"
               << "// DR (Decay Rate, 0-31):   " << dr << "\n"
               << "// SL (Sustain Level, 0-15): " << sl << "\n"
               << "// RR (Release Rate, 0-15): " << rr << "\n\n"
               << "const unsigned char sega_instrument[] = {\n"
               << "    // OP1,  OP2,  OP3,  OP4\n"
               << "    0x" << juce::String::toHexString(r30).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r30).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r30).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r30).paddedLeft('0', 2) << ", // Reg 30-3C: Detune & Multiple\n"
               << "    0x" << juce::String::toHexString(r40_op1).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r40_op2).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r40_op3).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r40_op4).paddedLeft('0', 2) << ", // Reg 40-4C: Total Level (OP4=0 is Carrier)\n"
               << "    0x" << juce::String::toHexString(r50).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r50).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r50).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r50).paddedLeft('0', 2) << ", // Reg 50-5C: Key Scale & Attack Rate\n"
               << "    0x" << juce::String::toHexString(r60).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r60).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r60).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r60).paddedLeft('0', 2) << ", // Reg 60-6C: AM & Decay Rate\n"
               << "    0x" << juce::String::toHexString(r70).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r70).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r70).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r70).paddedLeft('0', 2) << ", // Reg 70-7C: Sustain Rate\n"
               << "    0x" << juce::String::toHexString(r80).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r80).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r80).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r80).paddedLeft('0', 2) << ", // Reg 80-8C: Sustain Level & Release Rate\n"
               << "    0x" << juce::String::toHexString(r90).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r90).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r90).paddedLeft('0', 2) << ", 0x" << juce::String::toHexString(r90).paddedLeft('0', 2) << ", // Reg 90-9C: SSG-EG\n"
               << "    0x" << juce::String::toHexString(rB0).paddedLeft('0', 2) << ",                                     // Reg B0: Feedback & Algorithm (FB=6, ALG=4)\n"
               << "    0x" << juce::String::toHexString(rB4).paddedLeft('0', 2) << "                                      // Reg B4: Stereo Panning & LFO\n"
               << "};\n";

        return output;
    }

    /**
     * @brief Экспорт в формат GBDK C-Code для GameBoy Color.
     */
    static juce::String exportToGameBoyColor(int waveType, float pulseWidth, float attack, float decay, float sustain, float release)
    {
        juce::ignoreUnused(waveType);

        // 1. Скважность (NR11)
        unsigned char dutyBits = 0x80; // 50% по умолчанию
        juce::String dutyDesc = "50% Wave Duty";
        if (pulseWidth < 0.25f)
        {
            dutyBits = 0x00; // 12.5%
            dutyDesc = "12.5% Wave Duty";
        }
        else if (pulseWidth < 0.50f)
        {
            dutyBits = 0x40; // 25%
            dutyDesc = "25% Wave Duty";
        }
        else if (pulseWidth < 0.75f)
        {
            dutyBits = 0x80; // 50%
            dutyDesc = "50% Wave Duty";
        }
        else
        {
            dutyBits = 0xC0; // 75%
            dutyDesc = "75% Wave Duty";
        }

        // 2. ADSR -> Envelope (NR12)
        unsigned char nr12 = 0x00;
        juce::String envDesc;

        if (attack > 0.15f)
        {
            // Нарастание громкости: направление = 1 (вверх), стартуем с 0
            int sweepSteps = juce::jlimit(1, 7, static_cast<int>(attack * 7.0f));
            nr12 = (0x00 << 4) | (1 << 3) | sweepSteps;
            envDesc = "Sweep UP (Attack, steps: " + juce::String(sweepSteps) + ")";
        }
        else if (decay > 0.15f)
        {
            // Затухание: направление = 0 (вниз), стартуем с макс (15)
            int sweepSteps = juce::jlimit(1, 7, static_cast<int>(decay * 7.0f));
            nr12 = (0x0F << 4) | (0 << 3) | sweepSteps;
            envDesc = "Sweep DOWN (Decay, steps: " + juce::String(sweepSteps) + ")";
        }
        else
        {
            // Постоянная громкость: шаг = 0, уровень = sustain
            int sustainVol = juce::jlimit(0, 15, static_cast<int>(sustain * 15.0f));
            nr12 = (sustainVol << 4) | 0x00;
            envDesc = "Constant Volume (Sustain level: " + juce::String(sustainVol) + ")";
        }

        juce::String output;
        output << "// =========================================\n"
               << "// GAMEBOY COLOR GBDK C-CODE INITIALIZATION\n"
               << "// Generated by Antigravity VST3 Synthesizer\n"
               << "// =========================================\n\n"
               << "// Wave Duty: " << dutyDesc << "\n"
               << "// Envelope:  " << envDesc << "\n\n"
               << "// Enable Sound Controller\n"
               << "NR52_REG = 0x80; // Turn on APU sound controller\n"
               << "NR50_REG = 0x77; // Max volume for left & right channels\n"
               << "NR51_REG = 0x11; // Route Channel 1 to left & right channels\n\n"
               << "// Initialize Channel 1 Registers\n"
               << "NR10_REG = 0x00; // Sweep disabled\n"
               << "NR11_REG = 0x" << juce::String::toHexString(static_cast<int>(dutyBits)).paddedLeft('0', 2) << "; // Wave Duty cycle\n"
               << "NR12_REG = 0x" << juce::String::toHexString(static_cast<int>(nr12)).paddedLeft('0', 2) << "; // Initial Volume & Envelope\n"
               << "NR13_REG = 0x00; // Frequency Low Byte (dynamic)\n"
               << "NR14_REG = 0xC0; // Trigger note, Counter enabled\n";

        return output;
    }
};
